# This is an example configuration file
# You can add a yaml configuration file at any of the following locations:
#   $HOME/.config.yaml
#   $(PWD)/conf/config.yaml
#   $(PWD)/config.yaml
# Where the configuration will automatically be loaded.

## Turn debugging on
# debug: false

## Specify the location of scraped pages
output: "output"

## Specify your Yelp API keys
consumer_key: "RI2mrfWeg0RDcH2Pr8tNow"
consumer_secret: "vDXVcWQcbDggtbvIAj-wVOSyvh4"
access_token: "qrY6uy8vIqLUR6G693RxaXnYdsRYCQte"
access_token_secret: "rLVAuc6hvoh97Hcd0PMSHowzpQk"

## Specify database settings
database: "yelpdb"
collection: "review_collection"

## Specify the location of the model pickle file
# model_pickle: /path/to/model.pickle
