# This is an example configuration file
# You can add a yaml configuration file at any of the following locations:
#   $HOME/.config.yaml
#   $(PWD)/conf/config.yaml
#   $(PWD)/config.yaml
# Where the configuration will automatically be loaded.

## Turn debugging on
# debug: false

## Specify the location of scraped pages
output: "output"

## Specify your Yelp API keys
consumer_key: <super secret key>
consumer_secret: <super secret key>
access_token: <super secret key>
access_token_secret: <super secret key>

## Specify database settings
database: "yelpdb"
collection: "review_collection"

## Specify the location of the model pickle file
# model_pickle: /path/to/model.pickle
